services:
  cycle-bike:
    build:
      context: .
      dockerfile: src/adapters/CycleBike.Adapters.WebApi/Dockerfile
    image: cycle-bike:1.0.0
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=cycle-bike-api
    ports:
      - 8080:5161
    networks:
      - cycle-bike
    depends_on:
      - mongodb
      - redis
      - rabbitmq
      - psql
      - otel-collector
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
          
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    ports:
      - "18888:18888"
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
      - DOTNET_DASHBOARD_OTLP_ENDPOINT_URL=http://0.0.0.0:18889
    networks:
      - cycle-bike
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    networks:
      - cycle-bike
    depends_on:
      - aspire-dashboard
  
  mongodb:
    build: 
      context: .
      dockerfile: src/adapters/CycleBike.Adapters.Infrastructure/Modules/MongoDB/Dockerfile
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    networks:
      - cycle-bike

  psql:
    image: postgres:alpine3.23
    restart: always
    environment:
        POSTGRES_USER: username
        POSTGRES_PASSWORD: password
        POSTGRES_DB: cycle-bike
    ports:
      - 5432:5432
    networks:
      - cycle-bike
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - cycle-bike
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    depends_on:
      - mongodb

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - cycle-bike
    command: redis-server --user cycle-bike on nopass ~* &* +@all
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M


networks:
  cycle-bike:
    driver: bridge