<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>CycleBike.Adapters.gRPC</RootNamespace>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <ItemGroup>
      <Protobuf Include="Protos\bicycle_service.proto" GrpcServices="Both" Access="Public" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\core\Cycle.Core.Application\Cycle.Core.Application.csproj" />
      <ProjectReference Include="..\..\core\CycleBike.Core.Domain\CycleBike.Core.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Google.Protobuf" Version="3.34.1" />
        <PackageReference Include="Grpc.AspNetCore" Version="2.80.0" />
        <PackageReference Include="Grpc.AspNetCore.HealthChecks" Version="2.80.0" />
        <PackageReference Include="Grpc.AspNetCore.Server" Version="2.80.0" />
        <PackageReference Include="Grpc.Tools" Version="2.80.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>