<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-CycleBike.Adapters.OutboxRelay-555d1518-6f37-4b67-a981-d74783333180</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\core\CycleBike.Core.Common\CycleBike.Core.Common.csproj" />
      <ProjectReference Include="..\..\core\CycleBike.Core.Domain\CycleBike.Core.Domain.csproj" />
      <ProjectReference Include="..\CycleBike.Adapters.Infrastructure\CycleBike.Adapters.Infrastructure.csproj" />
    </ItemGroup>
</Project>
