//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CycleBike.Core.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CycleBike.Core.Common.Resources.ResourceMessages", typeof(ResourceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string API00001 {
            get {
                return ResourceManager.GetString("API00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string APL00001 {
            get {
                return ResourceManager.GetString("APL00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DOM00001 {
            get {
                return ResourceManager.GetString("DOM00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HTP00001 {
            get {
                return ResourceManager.GetString("HTP00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Get &apos;{0}&apos;.
        /// </summary>
        public static string INF00001 {
            get {
                return ResourceManager.GetString("INF00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache remove &apos;{0}&apos;.
        /// </summary>
        public static string INF00002 {
            get {
                return ResourceManager.GetString("INF00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache set &apos;{0}&apos;.
        /// </summary>
        public static string INF00003 {
            get {
                return ResourceManager.GetString("INF00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache exists &apos;{0}&apos;.
        /// </summary>
        public static string INF00004 {
            get {
                return ResourceManager.GetString("INF00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caches setted &apos;{0}&apos;.
        /// </summary>
        public static string INF00005 {
            get {
                return ResourceManager.GetString("INF00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caches getted &apos;{0}&apos;.
        /// </summary>
        public static string INF00006 {
            get {
                return ResourceManager.GetString("INF00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SKT00001 {
            get {
                return ResourceManager.GetString("SKT00001", resourceCulture);
            }
        }
    }
}
