<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.4"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1"/>
        <PackageReference Include="Moq" Version="4.20.72" />
        <PackageReference Include="xunit" Version="2.5.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\adapters\CycleBike.Adapters.GenericHttpClient\CycleBike.Adapters.GenericHttpClient.csproj" />
      <ProjectReference Include="..\..\adapters\CycleBike.Adapters.gRPC\CycleBike.Adapters.gRPC.csproj" />
      <ProjectReference Include="..\..\adapters\CycleBike.Adapters.Infrastructure\CycleBike.Adapters.Infrastructure.csproj" />
      <ProjectReference Include="..\..\adapters\CycleBike.Adapters.NotificationWorker\CycleBike.Adapters.NotificationWorker.csproj" />
      <ProjectReference Include="..\..\adapters\CycleBike.Adapters.OutboxRelay\CycleBike.Adapters.OutboxRelay.csproj" />
      <ProjectReference Include="..\..\adapters\CycleBike.Adapters.SocketAdapter\CycleBike.Adapters.SocketAdapter.csproj" />
      <ProjectReference Include="..\..\adapters\CycleBike.Adapters.SocketServerAdapter\CycleBike.Adapters.SocketServerAdapter.csproj" />
      <ProjectReference Include="..\..\adapters\CycleBike.Adapters.WebApi\CycleBike.Adapters.WebApi.csproj" />
      <ProjectReference Include="..\..\core\Cycle.Core.Application\Cycle.Core.Application.csproj" />
      <ProjectReference Include="..\..\core\CycleBike.Core.Common\CycleBike.Core.Common.csproj" />
      <ProjectReference Include="..\..\core\CycleBike.Core.Domain\CycleBike.Core.Domain.csproj" />
    </ItemGroup>

</Project>